FROM node:14-alpine

WORKDIR /home/node/app
COPY --chown=node:node . .
RUN npm install -g typescript

WORKDIR /home/node/app/backend
RUN npm install
RUN npm link typescript

WORKDIR /home/node/app/frontend
RUN npm install
RUN npm link typescript

WORKDIR /home/node/app

EXPOSE 5050
EXPOSE 5051

CMD ./dockerRunnerDev.sh