name: Lint and Test

on: [push, pull_request]

jobs:
  lint_frontend:
    defaults: 
      run:
        working-directory: frontend
    name: Check tsc, lint, and prettier on front end 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '21.x'
    - run: npm install
    - run: npm run lint
    - run: npm run prettier
      env:
        CI: true
  lint_backend: 
    defaults: 
      run:
        working-directory: backend 
    name: Check tsc, lint, and prettier on back end 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '21.x'
    - run: npm install
    - run: npm run lint
    - run: npm run prettier
      env:
        CI: true
  test_frontend:
    defaults: 
      run:
        working-directory: frontend
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }} on backend
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [21]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true

  test_backend:
    defaults: 
      run:
        working-directory: backend
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }} on backend 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [21]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true
